name: publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        aws-region: us-east-1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Setup Pandoc
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.14.0.3/pandoc-2.14.0.3-linux-amd64.tar.gz
        sudo tar zxvf pandoc-2.14.0.3-linux-amd64.tar.gz --strip-components=1 -C /usr/

    - run: pip install -r requirements.txt

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - run: cd tools && npm install

    - run: ./build.py --build-msg "<a href=\"https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}\">${GITHUB_SHA:0:8}</a>"

    - run: 'aws s3 sync .build s3://${S3_ENDPOINT}'
      env:
        S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}

    - run: 'aws --profile shaoner cloudfront create-invalidation --distribution-id ${CF_DISTRIBUTION} --paths "/*"'
      env:
        CF_DISTRIBUTION: ${{ secrets.CF_DISTRIBUTION }}
